sonar.projectKey=404SquadNotFound_SMB-GarasiBMW-Fullstack
sonar.organization=404squadnotfound

sonar.projectName=SMB-GarasiBMW-Fullstack
sonar.projectVersion=1.0

# Direktori source code
sonar.sources=app,database,routes,config
sonar.tests=tests

# Exclusions
sonar.exclusions=**/*.blade.php,vendor/**,storage/**,bootstrap/**,public/**

# Coverage report
sonar.php.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8